export const COLOURS = {
  white: "#ffffff",
  black: "#000000",
  green: "#00AC76",
  red: "#C04345",
  blue: "#0043F9",
  backgroundLight: "#F0F0F3",
  backgroundMedium: "#B9B9B9",
  backgroundDark: "#777777",
};

export const Items = [
  {
    id: 1,
    category: "bed",
    productName: "Comfortable bed",
    productPrice: 1799,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec dapibus lorem, vitae pulvinar mi. Etiam iaculis pulvinar iaculis. Vestibulum sit amet nunc a mi eleifend elementum. Vestibulum viverra neque in diam sodales, eu tincidunt lorem efficitur.",
    isOff: true,
    offPercentage: 10,
    productImage: require("../database/images/bed/a1.jpg"),
    isAvailable: true,
    productImageList: [
      require("../database/images/bed/a1.jpg"),
      require("../database/images/bed/a2.jpg"),
      require("../database/images/bed/a3.jpg"),
    ],
    count: 1,
  },
  {
    id: 2,
    category: "bed",
    productName: "Brown bed",
    productPrice: 1499,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec dapibus lorem, vitae pulvinar mi. Etiam iaculis pulvinar iaculis. Vestibulum sit amet nunc a mi eleifend elementum. Vestibulum viverra neque in diam sodales, eu tincidunt lorem efficitur.",
    isOff: false,
    productImage: require("../database/images/bed/b1.jpg"),
    isAvailable: true,
    productImageList: [
      require("../database/images/bed/b1.jpg"),
      require("../database/images/bed/b2.jpg"),
      require("../database/images/bed/b3.jpg"),
    ],
    count: 1,
  },
  {
    id: 3,
    category: "bed",
    productName: "good bed",
    productPrice: 1999,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec dapibus lorem, vitae pulvinar mi. Etiam iaculis pulvinar iaculis. Vestibulum sit amet nunc a mi eleifend elementum. Vestibulum viverra neque in diam sodales, eu tincidunt lorem efficitur.",
    isOff: true,
    offPercentage: 18,
    productImage: require("../database/images/bed/c1.jpg"),
    isAvailable: true,
    productImageList: [
      require("../database/images/bed/c1.jpg"),
      require("../database/images/bed/c2.jpg"),
      require("../database/images/bed/c3.jpg"),
    ],
    count: 1,
  },
  {
    id: 4,
    category: "chair",
    productName: "boAt chair",
    productPrice: 1999,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec dapibus lorem, vitae pulvinar mi. Etiam iaculis pulvinar iaculis. Vestibulum sit amet nunc a mi eleifend elementum. Vestibulum viverra neque in diam sodales, eu tincidunt lorem efficitur.",
    isOff: true,
    offPercentage: 18,
    productImage: require("../database/images/chair/a1.jpg"),
    isAvailable: true,
    productImageList: [
      require("../database/images/chair/a1.jpg"),
      require("../database/images/chair/a2.jpg"),
      require("../database/images/chair/a3.jpg"),
    ],
    count: 1,
  },
  {
    id: 5,
    category: "chair",
    productName: "boAt chair",
    productPrice: 1999,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec dapibus lorem, vitae pulvinar mi. Etiam iaculis pulvinar iaculis. Vestibulum sit amet nunc a mi eleifend elementum. Vestibulum viverra neque in diam sodales, eu tincidunt lorem efficitur.",
    isOff: false,
    productImage: require("../database/images/chair/b1.jpg"),
    isAvailable: true,
    productImageList: [
      require("../database/images/chair/b1.jpg"),
      require("../database/images/chair/b2.jpg"),
      require("../database/images/chair/b3.jpg"),
    ],
    count: 1,
  },
  {
    id: 6,
    category: "chair",
    productName: "boAt chair",
    productPrice: 1999,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec dapibus lorem, vitae pulvinar mi. Etiam iaculis pulvinar iaculis. Vestibulum sit amet nunc a mi eleifend elementum. Vestibulum viverra neque in diam sodales, eu tincidunt lorem efficitur.",
    isOff: false,
    productImage: require("../database/images/chair/c1.jpg"),
    isAvailable: false,
    productImageList: [
      require("../database/images/chair/c1.jpg"),
      require("../database/images/chair/c2.jpg"),
      require("../database/images/chair/c3.jpg"),
    ],
    count: 1,
  },
  {
    id: 7,
    category: "chair",
    productName: "boAt chair",
    productPrice: 1999,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec dapibus lorem, vitae pulvinar mi. Etiam iaculis pulvinar iaculis. Vestibulum sit amet nunc a mi eleifend elementum. Vestibulum viverra neque in diam sodales, eu tincidunt lorem efficitur.",
    isOff: false,
    productImage: require("../database/images/chair/d1.jpg"),
    isAvailable: true,
    productImageList: [
      require("../database/images/chair/d1.jpg"),
      require("../database/images/chair/d2.jpg"),
      require("../database/images/chair/d3.jpg"),
    ],
    count: 1,
  },
];
